name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.5
        with:
          GITHUB_TOKEN: h+fqasd4ZOdm0IxVRQVl3IKmENIB3AB5IeVSNK7J35LMG+/QzaZD26naD0CVfa7RbGeKv9EpV91f3SHR/SikY0l+IA2OT0607SWdDYxFYrbrPzEwG8N72UwwcCCO2hfscE68krRYt2zDoWY7chZeJsAHTcL0l5ap2k34AYiDnBUW1PffgAGoVLbBH1dcTRi3pYCx0rbsQYv06D3wkuGF/Yin04uuxFaE+aLIfKxJVAeeiKcsPEzVyZHDOI08r6lzRjtjT+p1HOgnPH08pLcHdpRC0lP9RK/xCPvbhj5zS0PnDqcbYjpWpLK1Jg8MzLaHTo3223ygMmiNLXZptb6anfuulLBpzYLetgLF4QZsQYQfkY/IdtGVR2oWtq+0v54qFeSOH88SQPqOtyKTj0WlBT343y+DoVbhLNKvSmxiWFE/fr2b7VXYqF/gllZHZdQ2WQfI1F/lHeWZtScZaRK5sq7ofyecCpNy+Hw55F2i1Q+YTdJD8VtD/Zmz3j+OTW6uMUKPxnBrHnK6hjrrTg/t+mVhP7Ui4voEuiv5SSdTwGd4iYLdFpOchmduGW0mRzAeES+TOExpWmLnYKkKgQ1XiZ4rX6woZNIVAk0wTHzl2DpYaCpDHYwhNlzIyLD0j4gmwdlE4JD5Ut1YLr+gnMcoLMxPLY96vMohRI0WML+38O0=
          BRANCH: master
          FOLDER: docs/build/html
          CLEAN: true
